architect:
  - ammaratef45
docker:
  as_root: true
  image: adamantium/flutter

install: |-
  curl -sSL https://get.rvm.io | bash -s stable --ruby
  gem install pdd
  gem install fastlane

decrypt:
  repo/zold_wallet/android/api-project.json: "repo/zold_wallet/android/api-project.json.asc"
  repo/zold_wallet/android/key.properties: "repo/zold_wallet/android/key.properties.asc"

merge:
  script: |-
    flutter doctor
    cd zold_wallet
    flutter packages get
    flutter test
    flutter -v build apk
    pdd -f /dev/null -v
    
deploy:
  script: |-
    flutter doctor
    cd zold_wallet
    flutter -v build apk
    fastlane supply init
    faslane beta
