architect:
  - ammaratef45
docker:
  image: ammaratef45/flutter:latest
install: |-
  sudo gem install pdd
  sudo gem install fastlane

decrypt:
  repo/zold_wallet/android/api-project.json: "repo/zold_wallet/android/api-project.json.asc"
  repo/zold_wallet/android/key.properties: "repo/zold_wallet/android/key.properties.asc"

merge:
  script: |-
    flutter doctor
    cd zold_wallet
    flutter packages get
    flutter test
    pdd -f /dev/null -v
    
deploy:
  script: |-
    flutter doctor
    cd zold_wallet
    flutter -v build apk
    fastlane supply init
    faslane beta
