architect:
  - ammaratef45
install: |-
  sudo gem install pdd
  sudo gem install fastlane
  git clone https://github.com/flutter/flutter.git -b beta --depth 1
  ./flutter/bin/flutter doctor

decrypt:
  zold_wallet/android/api-project.json: "zold_wallet/android/api-project.json.asc"
  zold_wallet/android/key.properties: "zold_wallet/android/key.properties.asc"

merge:
  script: |-
    cd zold_wallet
    ../flutter/bin/flutter packages get
    ../flutter/bin/flutter test
    pdd -f /dev/null -v
    
deploy:
  script: |-
    cd zold_wallet
    ../flutter/bin/flutter -v build apk
    fastlane supply init
    faslane beta
