version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: cd zold_wallet
      - run: flutter doctor
      - run: flutter packages get 
      - run: flutter test 
      - run: flutter -v build apk
