version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: ammaratef45/flutter:v3
    steps:
      - checkout
      - run: echo $secrets_file > zold_wallet/test/secret.dart
      - run: pdd -f /dev/null -v
      - run: flutter doctor && cd zold_wallet && flutter packages get && flutter test --coverage
      - codecov/upload:
          file: 'attendance/coverage/lcov.info'
