version: 2
jobs:
  build:
    docker:
      - image: ammaratef45/flutter:latest
    steps:
      - checkout
      - run: flutter doctor && cd zold_wallet && flutter packages get && flutter test
      - run: echo "$google_play_secret_key" | base64 --decode
      - run: echo "$key_properties" | base64 --decode

  deploy:
    docker:
      - image: ammaratef45/flutter:latest
    requires:
      - build
    filters:
      branches:
        only: master
    steps:
      - checkout
      - run:|
        cd zold_wallet/android
        gem install fastlane
        echo "$google_play_secret_key" | base64 --decode > api-project.json
        echo "$key_properties" | base64 --decode > key.properties
        flutter -v build apk
        fastlane supply init
        faslane beta

