version: 2
jobs:
  build:
    docker:
      - image: ammaratef45/flutter:latest
    steps:
      - checkout
      - run:
        name: Install
        command: |
          flutter doctor
          cd zold_wallet
          flutter packages get 
          flutter test
          flutter -v build apk

  deploy:
    docker:
      - image: ammaratef45/flutter:latest
    requires:
      - build
    filters:
      branches:
        only: master
    steps:
      - checkout
      - run:|
        cd zold_wallet/android
        gem install fastlane
        echo "$google_play_secret_key" | base64 --decode > api-project.json
        fastlane supply init
        faslane beta

