version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter:latest
    steps:
      - checkout
      - run: flutter upgrade
      - run: flutter doctor
      - run: cd zold_wallet && flutter packages get 
      - run: cd zold_wallet && flutter test 
      - run: cd zold_wallet && flutter -v build apk
