version: 2
jobs:
  build:
    docker:
      - image: adamantium/flutter:latest
    steps:
      - checkout
      - run: echo secrets_file > zold_wallet/test/secret.dart
      - run: flutter doctor && cd zold_wallet && flutter packages get && flutter test
